locale: "en-US"
title: "Hwanhee Kim"
name: "Hwanhee Kim"
description: "Master's Student in Robotics Program at KAIST"
url: "https://khhandrea.github.io"
baseurl: ""
repository: "khhandrea/khhandrea.github.io"
logo: "/images/others/profile.jpeg"

author:
  name: "Hwanhee Kim"
  avatar: "images/others/profile.jpeg"
  bio: "Master's Student in Robotics Program at KAIST"
  location: "Daejeon, South Korea"
  employer: "KAIST"
  email: "khhandrea@kaist.ac.kr"
  cv: "https://drive.google.com/file/d/1t5_VwR6ZMVMoZc955AIB3dOgf9lMz6CG/view?usp=drive_link"
  github: "khhandrea"
  linkedin: "hwanhee-kim-345aba36b"
  twitter: "gimani02"
  orcid: "0009-0000-7575-1536"

markdown: kramdown
encoding: "utf-8"
timezone: "Asia/Seoul"
